openapi: 3.0.3
info:
  title: Cart Service
  description: Microservice for managing carts in the Amazing project. This service allows users to add, remove, view, and clear products in their carts.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Development server
paths:
  /carts/users/{pseudo}/products/{productId}:
    parameters:
      - name: pseudo
        in: path
        required: true
        schema:
          type: string
        example: Hunter2
        description: Pseudo of the user
      - name: productId
        in: path
        required: true
        schema:
          type: string
        example: 12345
        description: ID of the product
    post:
      summary: Add product to the user's cart
      description: Adds the product with ID `productId` to the cart of the user `pseudo`. Verifies that both the user and product exist before adding.
      responses:
        404:
          description: User or product not found
        201:
          description: Product successfully added to the user's cart

    delete:
      summary: Remove product from the user's cart
      description: Removes the product with ID `productId` from the cart of the user `pseudo`. Verifies that both the user and product exist before removing.
      responses:
        404:
          description: User or product not found
        200:
          description: Product successfully removed from the user's cart

  /carts/users/{pseudo}:
    parameters:
      - name: pseudo
        in: path
        required: true
        schema:
          type: string
        example: Hunter2
        description: Pseudo of the user
    get:
      summary: Retrieve user's cart
      description: Retrieves the list of products in the user's cart. The product details come from the product service.
      responses:
        404:
          description: User not found
        200:
          description: Cart retrieved successfully
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CartItem'

    delete:
      summary: Clear user's cart
      description: Removes all products from the cart of the user `pseudo`.
      responses:
        404:
          description: User not found
        200:
          description: Cart successfully cleared

  /carts/products/{productId}:
    parameters:
      - name: productId
        in: path
        required: true
        schema:
          type: string
        example: 12345
        description: ID of the product
    delete:
      summary: Remove product from all carts
      description: Removes the product with ID `productId` from all user carts.
      responses:
        404:
          description: Product not found in any cart
        200:
          description: Product successfully removed from all carts

components:
  schemas:
    CartItem:
      type: object
      properties:
        id:
          type: integer
          description: Autogenerated ID of the cart item
        productId:
          type: string
          description: ID of the product
        pseudo:
          type: string
          description: Pseudo of the user
      example:
        id: "7890"
        productId: "12345"
        pseudo: "Haisen"
